# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: GitHub Actions Demo

on:
  repository_dispatch:
    types: [run_my_workflow]

jobs:
  Example-Actions-Job:
    name: Exploring GitHub Actions
    runs-on: ubuntu-latest
  
    steps:
      - run: echo "Payload field is ${{ github.event.client_payload.mydata }}"
      - run: echo "The job was triggered by ${{ github.event_name }} event."
